indice-co/Indice.Platform

- src/Indice.AspNetCore.Identity/Data/Mappings/UserDeviceMap.cs
The previous implementation was using the same date always, which was the date the migration was created
> fix on default date value release/3.1.0

- src/Indice.AspNetCore.Identity/Data/Mappings/UserDeviceMap.cs
- src/Indice.AspNetCore.Identity/Features/PushNotifications/DevicesController.cs
The previous implementation was using the same date always, which was the date the migration was created
> fix on default date value

- src/Indice.AspNetCore.Identity/Features/PushNotifications/DevicesController.cs
There are cases where the pnsHandle, provided from mobile services provider(Apple,Google) can change.
For these cases we must update the device installation on notifications hub with the new pnsHandle.
The update process is being handled by NotificationHub.CreateOrUpdateInstallationAsync which is called in the PushNotificationServiceAzure.Register method
> remove check for enabled push notifications on the device

- src/Indice.AspNetCore.Identity/Services/TotpService.cs
Send token in notification's template data so that it can be easily retrieved from clients
> send notification token in payload data

- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Controllers/ClientsController.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Controllers/ResourcesController.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Requests/ClientRequests.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Requests/ResourceRequests.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Responses/ApiResourceInfo.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Responses/ApiScopeInfo.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Responses/ClientInfo.cs
- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Responses/IdentityResourceInfo.cs
I've added (completed, to be precise) translations to `Client` and `ApiScopes` Entities via their corresponding `Properties` navigation property.
A new `TranslationDictionary<T>` class has been added to keep the translations logic into one place.
We need to set names/descriptions for clients and scopes in more than one language.
I've tested all CRUD operations with swagger for Client and ApiScopes.
There is no code written for `delete` actions because there is a cascade delete on the database for the FK's.
> Translations feature for Client & ApiScopes

- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Controllers/ResourcesController.cs
At my previous PR (#33 ) I had two mistakes
- I had declared a non static private method that caused the following error 
```text
Client projection contains reference to constant expression of 'Indice.AspNetCore.Identity.Api.Controllers.ResourcesController' through instance method 'GetTranslationsFromApiScope'. This could potentially cause memory leak. Consider making the method static so that it does not capture constant in the instance. See https://go.microsoft.com/fwlink/?linkid=2103067 for more information.
```
- A wrong `.Include` for `ApiScopes.Properties`
This PR is a fix for those two errors.
> Fix non-static method and DbContext Include for ApiScope Properties

- src/Indice.AspNetCore.Identity/Services/DeveloperTotpService.cs
- src/Indice.AspNetCore.Identity/Services/TotpService.cs
- src/Indice.Common/Configuration/PushNotificationMessage.cs
- src/Indice.Common/Configuration/PushNotificationMessageBuilder.cs
- src/Indice.Common/Services/IPushNotificationService.cs
- src/Indice.Common/Services/ITotpService.cs
- test/Indice.AspNetCore.Identity.Tests/Services/MockTotpService.cs
- test/Indice.Services.Tests/PushNotificationMessageTests.cs
I've added a new optional parameter `string data = null` to the `ITotpService.Send` method so we can handle structed objects when the delivery channel is `PushNotification`.
As consumer we want to do something like the following
```cs
var pushNotificationMessage = "Business Message Here"; // eg "Please approve the transaction from your account *1234"
var serializedData = "{{ \"connectionId\": \"123\", \"otp\": \"{0}\", \"moreData\": [ ...  ] }}"
var totpResult = await totpService.Send(principal,  message: pushNotificationMessage, deliveryChannel, purpose: "purpose", data: serializedData);
```
And then the client will handle the deserialization of the structured data.
For existing consumers or if the consumer does not need to send json message to the client, by ignoring the `data` …
> Add data parameter in ITotpService.Send to be able to send complex data to the mobile client when delivery channel is PushNotification

- src/Indice.AspNetCore.Identity/Services/TotpService.cs
I've added a new provider to support `PushNotifications` in Identity.
Our consent page must support our new feature "Push Approvals" and we realised that there is no such provider.
No testing have been done.
Nope.
> Add PushNotification TotpProvider

- src/Indice.AspNetCore.Identity/Features/Totp/TotpController.cs
- src/Indice.Common/Services/ITotpService.cs
I've added a new builder to the `TotpMessageBuilder` in order to include the data the client is sending.
We have made some changes with PR #46, but I missed the fact that our consumer is using a delegate service to do a HTTP call to `OtpController`, instead of using the `ITotpService` directly.
I've tested with swagger UI that the controller receives the parameter and the builder is building the message as it should. The example request I was testing is
```json
{
"channel": "PushNotification",
"purpose": "A purpose",
"message": "This is the push message",
"data": "{{\"transMetadata\":[{{\"label\":\"TransactionHeader\",\"value\":\"Transaction Test Header\"}},{{\"label\":\"TransactionMessage\",\"value\":\"Transaction Message \\u03C3\\u03C4\\u03B1 …
```
> Add ITotpDataBuilder to TotpMessageBuilder when building a TotpMessage from the OtpController

- src/Indice.AspNetCore.Identity/Features/IdentityServerApi/Models/Filters/UserDeviceFilter.cs
- src/Indice.AspNetCore.Identity/Features/PushNotifications/DevicesController.cs
I've added filtering options to `GetDevices` action in `DevicesController` but only for the `IsPushNotificationEnabled` property.
The filter supports 3 values
- `null` fetch all user devices (default value)
- `true` fetch all user devices with `IsPushNotificationEnabled = true`
- `false` fetch all user devices with `IsPushNotificationEnabled = false`
We've noticed that the `GetDevices` action is fetching all the devices and we are filtering the deleted ones in the client.
I've added some data to my localDb and tested with Postman and SqlProfiler that the query and data are correct. Here are the results
```sql
exec sp_executesql N'SELECT [u].[DeviceId], [u].[DeviceName], [u].[DevicePlatform], [u].[IsPushNotificationsEnabled]
FROM [auth].[UserDevice] AS [u]
WHERE [u].[UserId] = …
```
> Add UserDeviceFilter to GetDevices

- src/Indice.AspNetCore.Identity/Features/TrustedDeviceAuthorization/Endpoints/InitRegistrationEndpoint.cs
- src/Indice.AspNetCore.Identity/IdentityResources.Designer.cs
- src/Indice.AspNetCore.Identity/IdentityResources.resx
- src/Indice.AspNetCore.Identity/Services/IdentityMessageDescriber.cs
I've add a new resource in `IdentityMessageDescriber` for the device registration otp code.
Clients needs custom text for this message. Something like `Κωδικός Otp {otp} για την εγγραφή της συσκευής σας {{device name}} μέσω mobile banking. Ο κωδικός ισχύει 2 λεπτά.`
No testing
Nope.
> Add Dynamic otp message for device registration in InitRegistrationEndpoint

- src/Indice.AspNetCore.Identity/Features/Totp/TotpController.cs
- src/Indice.AspNetCore.Identity/Services/DeveloperTotpService.cs
- src/Indice.AspNetCore.Identity/Services/TotpService.cs
- src/Indice.Common/Configuration/PushNotificationMessage.cs
- src/Indice.Common/Configuration/PushNotificationMessageBuilder.cs
- src/Indice.Common/Services/IPushNotificationService.cs
- src/Indice.Common/Services/ITotpService.cs
- src/Indice.Services/PushNotificationServiceAzure.cs
- test/Indice.AspNetCore.Identity.Tests/Services/MockTotpService.cs
- test/Indice.Services.Tests/Indice.Services.Tests.csproj
- test/Indice.Services.Tests/PushNotificationMessageTests.cs
I've added a new parameter `classification` to the `TotpService` and `IPushNotification`. This is a breaking change. Also we had to update the iOS and Android templates.
We need to classify the push notification messages to the mobile clients (eg "PushApprovals", "Marketing", "Information") so the client will be able to handle all those cases differently, and of course, avoid "weird notifications" for new categories in old clients.
I've created the nuget packages locally, updated them to the Consumer project and tested with real device.
Scenarios
- Send push notification to an old client (registered without classification) and the new template -> `Passed` 
- Send push notification to new client (registered with classification) and the new template -> `Passed`
Windows Phone template has …
> Add PushNotification Classification in TotpService

- src/Indice.AspNetCore.Identity/Features/TrustedDeviceAuthorization/Endpoints/InitRegistrationEndpoint.cs
- src/Indice.AspNetCore.Identity/Services/IdentityMessageDescriber.cs
I've added a new parameter to Resource `DeviceRegistrationCodeMessage`
Clients needs to distinguish between interaction mode in messages. 
- Current Message `OTP CODE: {0} FOR YOUR DEVICE REGISTRATION {1} VIA MOBILE BANKING. IT WILL BE VALID FOR 2 MINUTES.`
- Requested Message `OTP CODE: {0} FOR YOUR DEVICE {1} USING {2} VIA MOBILE BANKING. IT WILL BE VALID FOR 2 MINUTES.` where `{2}` is `Fingerprint` or `Pin`
> Add InteractionMode parameter to DeviceRegistrationCodeMessage

- src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html
- src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts
When a case type is configured with the following property  
`{ "boOptions": { "hidePdf": true } }`
the pdf button will be hidden in all checkpoints and modes (draft or published)
> Cases UI - Hide Pdf button from case type config property

- src/Indice.Features.Cases.AspNetCore/Events/CaseMessageCreatedEvent.cs
- src/Indice.Features.Cases.AspNetCore/Models/Message.cs
- src/Indice.Features.Cases.AspNetCore/Services/CaseMessageService/BaseCaseMessageService.cs
Add a new `CaseMessageCreatedEvent` for handling events before saving the message to the database.
example scenario:
When a user uploads an attachment, do someting before saving the file to the storage.
> Add CaseMessageCreatedEvent

- src/Indice.AspNetCore.Identity/Features/Devices/DevicesController.cs
Based on [this](https://github.com/indice-co/Indice.AspNet/blob/feature/user-devices-count/src/Indice.AspNetCore.Identity/Features/Devices/DevicesController.cs#L112), changed the `deviceId` property with `device.Id` for register and unregister device actions.
> Use device.id as the key for push notification service

- src/Indice.AspNetCore.Identity/Services/Totp/TotpServiceUser.cs
fix a bug in push notification data, where otp property is null
> add augmentedData to TotpMessage

- src/Indice.Features.GovGr/GovGrClient.cs
The KycOptions were misspelled when creating a new GovGrKycClient
> Fixed govGrClient Kyc settings

- src/Indice.Common/Serialization/JsonObjectToInferredTypeConverter.cs
There is a case where the `case data` are an array of objects, which translates to `Newtonsoft..JArray`.
> Add support for "JArray" in JsonObjectToInferredTypeConverter

- src/Indice.Services/Extensions/IConfigurationExtensions.cs
According to [this](https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcoreold%2Cnetcore6):
_On March 31, 2025, support for instrumentation key ingestion will end. Instrumentation key ingestion will continue to work, but we'll no longer provide updates or support for the feature. Transition to connection strings to take advantage of new capabilities._
So, I just added a new GetApplicationInsightsConnectionString extension method.
> add GetApplicationInsightsConnectionString extension method

- src/Indice.Features.Cases.AspNetCore/Data/Config/DbCaseTypeConfiguration.cs
New maximum needed to cater to the new descriptions at Chania Bank.
> Minor change to the CaseType Description length.

- src/Indice.Features.Cases.App/src/styles.scss
Η λίστα, που απαιτούσε xl motinors, πλέον εμφανίζεται σωστά μέχρι και σε medium οθόνες (tablets).
> override list-view properties to improve responsiveness

- src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
- src/Indice.Features.Cases.AspNetCore/CasesApiConstants.cs
- src/Indice.Features.Cases.AspNetCore/CasesApiFeatureExtensions.cs
- src/Indice.Features.Cases.AspNetCore/CasesApiOptions.cs
- src/Indice.Features.Cases.AspNetCore/Controllers/AdminNotificationsController.cs
- src/Indice.Features.Cases.AspNetCore/Controllers/MyCaseTypesController.cs
- src/Indice.Features.Cases.AspNetCore/Controllers/MyCasesController.cs
With this bugfix you can now configure 2 separate endpoints groups and api explorer groups correctly.
Read `CHANGELOG` for code migrations.
closes #225.
> GroupName & ApiName bugfixes

- src/Directory.Build.props
- src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
- src/Indice.Features.Cases.AspNetCore/Models/Responses/MyCasePartial.cs
- src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
A my-cases consumer SPA (with access only to `MyCases` endpoints), requires the metadata property to be included in my-cases list response.
If we are behind a case proxy, it's fine, we can hide the metadata from the SPA. However, in this case, are there any concerns related to security or sensitive data that should not be shown in the `case.metadata` property? We are allowing the developer to create a case with any metadata they choose.
> Add case metadata to my-case list

- src/Indice.Features.Cases.AspNetCore/Data/Models/DbAttachment.cs
- src/Indice.Features.Cases.AspNetCore/Workflows/Activities/SendMessageActivity.cs
Add `RunAsSystemUser` to handle authorization exceptions when the workflow is trying to move from checkpoint type A to B, and the context user has not membership for checkpoint B.
> Add RunAsSystemUser property to SendMessage Activity

- src/Indice.Features.Identity.Core/ExtendedUserManager.cs
**Scenario**:
- Event handling and UpdateAsync throws an ConcurrencyFailure exception in EF Core
**Hotfix**:
- Ensure that user instance gets updated successfully, before publishing the UserBlockedEvent
> Fix for ConcurrencyFailure in EF Core

- src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts
- src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts
A user assigns a case to himself and the case which doesnt have an `AwaitEdit` after the assignment unlocks the form in an editable state (if the page reloads this goes away).
The `layout` of the form was reset in `ngOnChanges` and the check to make the form read-only could not be executed since the change was not triggered by the `formEditable` property.
In the `ngOnChanges` check the `formEditable` property directly.
> Fix: case-form becomes editable after assign

- src/Indice.Features.Identity.UI/Pages/Register.cshtml.cs
After completing registration I am redirected to the identity login page instead of the page that started it (redirect URL was sent)
Set the `ReturnURL` on the input model when the get method of the page is called.
> fix: RegisterInputModel.ReturnUrl was not set

- src/Indice.Features.Identity.Server/Totp/TotpHandlers.cs
Dynamic Data object is missing when the OTP delivery channel is Email
> Add missing data when OTP delivery channel is Email

- src/Indice.Features.GovGr/CHANGELOG.md
- src/Indice.Features.GovGr/Configuration/ConfigurationExtensions.cs
- src/Indice.Features.GovGr/Configuration/GovGrOptions.cs
- `BusinessRegistryOptions.Enabled` option for backwards compatibility with previous installations. Consumers that require Business Registry feature will have to configure this option.
> Add BusinessRegistryOptions.Enabled configuration

- src/Indice.Features.Identity.Core/Events/UserNameChangedEvent.cs
- src/Indice.Features.Identity.Core/ExtendedUserManager.cs
Add support for accessing the previous user state in the `UserNameChangedEvent `.
> Enrich UserNameChangedEvent with previous user state

- src/Indice.Features.Messages.Core/Manager/NotificationsManager.cs
The `NotifiactionsManager` `SendMessageToRecipients` method that accepts a `templateId` doesn't parse the content type to the Enum correctly.
It does `template.Content.ToDictionary(x => Enum.Parse<MessageChannelKind>(x.Key), x => x.Value)`
It should do `template.Content.ToDictionary(x => Enum.Parse<MessageChannelKind>(x.Key, ignoreCase: true), x => x.Value)`
as done in other places (`CampaingsService`, `TemplateService`, `ToCreateCampaignCommand`) inside the Messages project.
> Fix Messages NotificationManager.SendMessageToRecipients doesn't parse content correctly

- src/Indice.Features.Messages.Core/Services/Validators/CreateCampaignRequestValidator.cs
Fixes the swagger generation error for the messages admin endpoint `CreateCampaign` by assigning a key to the rule that was for the entire model and not for a specific property in the `CampaignRequestValidator<CreateCampaignRequest>`.
> Fix messages admin endpoint swagger

- src/Indice.Features.Identity.UI/Resources/Pages/Shared/EmailRegister.el.resx
Αλλαγή λεκτικού στο EmailRegister template γιατί το κείμενο ερχόταν ως εξής:
> Greek translation fix in register email template.

- src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
- test/Indice.Features.Cases.AspNetCore.Tests/CasesDbContextTestExtensions.cs
- test/Indice.Features.Cases.AspNetCore.Tests/MyCaseServiceTests.cs
When a case data filter was applied (e.g., `data.someId::eq::(string)123ABC`) to the GetMyCases endpoint, we executed the results first and then applied the filtering. 
This led to issues with pagination since we had a default of 100 all this time, and we were unaware of it.
> Bugfix on caseData filter

- src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
- src/Indice.Features.Cases.AspNetCore/CasesApiFeatureExtensions.cs
The default behaviour will clean up completed wf instances when their age is 30 days or more.
> Change default behaviour of Elsa CleanUpOptions

- src/Directory.Build.props
- src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/label-only/label-only.component.html
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/label-only/label-only.component.scss
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/label-only/label-only.component.spec.ts
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/label-only/label-only.component.ts
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/tailwind-framework.component.ts
- src/Indice.Features.Cases.App/src/app/shared/shared.module.ts
- src/Indice.Features.Cases.UI/CHANGELOG.md
- **New** Cases UI widget component (**label-only**) for usage in _Layout.json_. Displays form input data as a simple label. Supports enum & currency type conversions.
- **Disables** _Add button_ from _readonly_ array types in Cases UI.
- Other _readonly_ array type improvements.
> Feature/case management/introduce label only cases app widget

- src/Indice.Features.Cases.App/package.json
- src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
- src/Indice.Features.Cases.UI/CHANGELOG.md
When clicking on specific case type from the menu, the filter can now no longer be removed
> Feature/case management/make case type filter readonly

- src/Indice.AspNetCore/Indice.AspNetCore.csproj
- src/Indice.Features.Identity.Core/TokenCreation/ExtendedTokenCreationService.cs
Fix Bearer token not passing validation because security keys differ from .NET 7 and .NET 8 version of the Nuget package
**Error message:**
`Bearer was not authenticated. Failure message: IDX10500: Signature validation failed. No security keys were provided to validate the signature.`
**More details here:**
https://stackoverflow.com/questions/60635967/idx10500-signature-validation-failed-no-security-keys-were-provided-to-validat
> Fix Bearer token not passing validation

- src/Indice.Features.Identity.Core/DeviceAuthentication/Configuration/Constants.cs
- src/Indice.Features.Identity.Core/DeviceAuthentication/Endpoints/InitRegistrationEndpoint.cs
- src/Indice.Features.Identity.Core/DeviceAuthentication/Stores/UserDeviceStoreEntityFrameworkCore.cs
- src/Indice.Features.Identity.Core/DeviceAuthentication/Validation/CompleteRegistrationRequestValidator.cs
We need to differentiate between the 4-pin and biometric purposes during device registration. 
Users completing the process in less than 30 seconds are encountering the error: `Last token has not expired yet. Please wait a few seconds and try again`.
> Add InteractionMode property to otp purpose during device authentication

- src/Indice.Services/PushNotificationServiceAzure.cs
We need to send a Push Notification body using the existing `"body": "$(body)"` parameter.
> Add push notification body to all azure hub notification templates

- src/Indice.Features.GovGr/GovGrKycScopeDescriber.cs
- src/Indice.Features.GovGr/GovGrKycScopes.cs
- src/Indice.Features.GovGr/Models/KycModels.cs
- src/Indice.Features.GovGr/Resources/GovGrKycScopeDescriber.el.resx
- src/Indice.Features.GovGr/Resources/GovGrKycScopeDescriber.en.resx
- src/Indice.Features.GovGr/Resources/GovGrKycScopeDescriber.resx
New GovGR changes:
- Three new scopes added: `ElectricitySupplyPoint, GasSupplyPoint and IdentityBasic`
- New models added: `unemploymentInfo, pensionerInfo, academicInfo, iekStudentInfo`
- `FamilyStatus` scope to be removed
> Changes to GovGr models and scopes

- src/Directory.Build.props
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/file-widget/file-widget.component.html
- src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/tailwind-framework.component.ts
- src/Indice.Features.Cases.App/src/styles.scss
- src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
"Choose file" button now respects readonly option set in layout and added mb-4 to the every element of the case details
> File attachment respects readonly

- src/Indice.AspNetCore/Filters/AllowedFileSizeAttribute.cs
- src/Indice.Features.Cases.AspNetCore/CasesApiConstants.cs
- src/Indice.Features.Cases.AspNetCore/CasesApiOptions.cs
- src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs
- src/Indice.Features.Cases.AspNetCore/Controllers/MyCasesController.cs
Modify the `AllowedFileSizeAttribute` to allow overriding the file size limit, by providing an optional configuration key name.
> Add option for controlling AllowedFileSizeAttribute file size limit

- src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
Calling GetAttachmentByField while a property is filled with an empty string will no longer be problematic. You can safely reset fields by setting them to an empty string.
> GetAttachmentByField parsing fix
