indice-co/Indice.Platform

src/Indice.AspNetCore.Identity/Data/Models/UserDevice.cs, src/Indice.AspNetCore.Identity/Features/PushNotifications/DevicesController.cs
=> Develop - psysical deletion of device

src/Indice.Services/Extensions/BlobPropertiesExtensions.cs, src/Indice.Services/FileServiceAzureStorage.cs, test/Indice.Services.Tests/BlobPropertiesExtensionsTest.cs
Workaround for https://github.com/Azure/azure-sdk-for-net/issues/22877
=> eTag invalid format workaround

src/Indice.Features.Cases.App/package.json, src/Indice.Features.Cases.App/src/app/features/cases/cases.component.ts
add text to view-layout button
=> add text to view-layout button

src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/date-widget/date-widget.component.html, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/date-widget/date-widget.component.ts
add min & max options to date widget
=> add min & max options to date widget

src/Indice.Features.Cases.App/src/app/features/dashboard/dashboard.component.ts
Remove the Date from dashboard
=> remove date from dashboard

src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.html, src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.ts
Disable submit button when opt in/out is not changed
=> disable submit button when value is not changed

src/Indice.Features.Cases.App/src/app/features/case-types/case-type-delete-modal/case-type-delete-modal.component.html, src/Indice.Features.Cases.App/src/app/features/case-types/case-type-delete-modal/case-type-delete-modal.component.ts, src/Indice.Features.Cases.App/src/app/features/case-types/case-types.component.ts, src/Indice.Features.Cases.App/src/app/features/case-types/case-types.service.ts, src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs
Όταν διαγράφουμε το case type, θα διαγράφονται και τα αντίστοιχα checkpoint types και role case types
=> Deleting a case type bug fixes.

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-print-pdf/case-print-pdf.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/cases.module.ts, src/Indice.Features.Cases.App/src/app/shared/components/approval-buttons/approval-buttons.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/case-warning-modal/case-warning-modal.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-warning-modal/case-warning-modal.component.ts
Conditionally show a warning modal when user clicks the Approve button
=> Show warning modal on approve

src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseDetails.cs, src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/BaseCaseService.cs
Add all approver `AuditMeta` order by created asc
=> add Approvers list to case details

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html
=> separate Client metadata and add role

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-detail-info/case-detail-info.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-detail-info/case-detail-info.component.ts, src/Indice.Features.Cases.App/src/app/shared/shared.module.ts
=> Separate even more

src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
return latest data when case is completed
=> return latest data when case is completed

src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseTypePartial.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
=> translate my case types

src/Indice.Features.Cases.AspNetCore/Controllers/MyCasesController.cs, src/Indice.Features.Cases.AspNetCore/Interfaces/IMyCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
Add a get case Data endpoint to retrieve Case Data only
=> Add GetCaseData endpoint

src/Indice.Features.Cases.AspNetCore/Controllers/MyCasesController.cs, src/Indice.Features.Cases.AspNetCore/Data/Models/CasePublicStatus.cs, src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
=> filter my cases public status

src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
add filters to GetMyCasesListFilter
=> Get my cases list filter

src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
add filter clause for case data
=> add filter clause for case data

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/submit-widget/submit-widget.component.ts
=> cases bo UI improvements

src/Indice.Features.Cases.AspNetCore/Controllers/MyCasesController.cs, src/Indice.Features.Cases.AspNetCore/Data/Models/DbCase.cs, src/Indice.Features.Cases.AspNetCore/Interfaces/IMyCaseService.cs, src/Indice.Features.Cases.AspNetCore/Models/Responses/MyCasePartial.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
Also created an endpoint/service to be able to change it.
=> Add IsRead Property to the DbCase Model

src/Indice.Features.Cases.App/src/app/core/services/cases-api.service.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/submit-widget/submit-widget.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/case-custom-action/case-custom-action.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-custom-action/case-custom-action.component.ts, src/Indice.Features.Cases.AspNetCore/Controllers/AdminWorkflowInvokerController.cs, src/Indice.Features.Cases.AspNetCore/Models/ActionRequest.cs, src/Indice.Features.Cases.AspNetCore/Models/CaseActions.cs, src/Indice.Features.Cases.AspNetCore/Models/CustomCaseAction.cs, src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseDetails.cs, src/Indice.Features.Cases.AspNetCore/Services/BaseCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseActionsService.cs, src/Indice.Features.Cases.AspNetCore/Workflows/Activities/AwaitActionActivity.cs, src/Indice.Features.Cases.AspNetCore/Workflows/Interfaces/IAwaitActionInvoker.cs, src/Indice.Features.Cases.AspNetCore/Workflows/Services/AwaitActionInvoker.cs
enrich case-custom action & minor UI improvements
=> enrich case-custom action & minor UI improvements

src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
=> add case metadata filter

src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/lookup-widget/lookup-widget.component.ts
add change detection in lookup widget
=> add change detection in lookup widget

src/Indice.Features.Cases.App/src/app/core/services/cases-api.service.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/approval-buttons/approval-buttons.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/case-custom-action/case-custom-action.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-custom-action/case-custom-action.component.ts, src/Indice.Features.Cases.AspNetCore/Models/CustomCaseAction.cs, src/Indice.Features.Cases.AspNetCore/Models/SuccessMessage.cs, src/Indice.Features.Cases.AspNetCore/Models/Toaster.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseActionsService.cs, src/Indice.Features.Cases.AspNetCore/Workflows/Activities/AwaitActionActivity.cs
extend custom action functionality & UI improvements
=> extend custom action functionality & UI improvements

src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs, src/Indice.Features.Cases.AspNetCore/Services/CheckpointTypeService.cs, src/Indice.Features.Cases.AspNetCore/Services/RoleCaseTypeService.cs
checkpoint type code filter bug fix
=> checkpoint type code filter bug fix

src/Indice.Features.Cases.AspNetCore/Workflows/Specifications/WorkflowDefinitionTagCsvSpecification.cs
fix workflow definition tag csv specification bug
=> fix workflow definition tag csv specification bug

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Data/Config/DbCaseConfiguration.cs, src/Indice.Features.Cases.AspNetCore/Data/Models/DbCase.cs, src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseMessageService/BaseCaseMessageService.cs
- `CurrentCheckpoint` logic for BO users. This is a performance optimization
=> Add CurrentCheckpoint logic for cases

src/Indice.Features.Cases.AspNetCore/Services/BaseCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
CaseType translation when getting case by Id.
Fix needed both for web and mobile clients.
=> CaseType translation when getting case by Id.

src/Indice.Features.GovGr/CHANGELOG.md, src/Indice.Features.GovGr/Indice.Features.GovGr.csproj
Reference: https://github.com/dotnet/aspnetcore/issues/39181
=> downgrade Microsoft.IdentityModel.Tokens to 6.14.1

src/Indice.AspNetCore.Identity/CHANGELOG.md
Added a changelog for the breaking changes after version 6.4.0 at the [Identity project](https://github.com/indice-co/Indice.AspNet/tree/master/src/Indice.AspNetCore.Identity)
=> UserDevice table breaking changes

src/Indice.Features.Cases.App/src/app/core/services/cases-api.service.ts, src/Indice.Features.Cases.App/src/app/features/case-types/case-type-create/case-type-create.component.ts, src/Indice.Features.Cases.App/src/app/features/case-types/case-types.service.ts, src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Indice.Features.Cases.AspNetCore.csproj, src/Indice.Features.Cases.AspNetCore/Models/CaseTypeRequest.cs, src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseType.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs, src/Indice.Features.Cases.UI/CHANGELOG.md
- Case type form for create/update is simplified
- redesign case type form with tabs and 3 sections (cate type, members & checkpoints)
- deleted code will be used in future work
=> Remove checkpoints & members from case type admin form

src/Indice.Features.Cases.AspNetCore/Services/AdminReportService.cs
This is what happens when your middle name is "CTRL + C, CTRL + V"...
=> bug fix in report service

src/Indice.Features.Cases.App/src/app/shared/components/select-case-type/display-case-types/display-case-types.component.html, src/Indice.Features.Cases.App/src/app/shared/components/select-case-type/display-case-types/display-case-types.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/select-case-type/select-case-type.component.html, src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs, src/Indice.Features.Cases.UI/CHANGELOG.md
Add Categories & Ordering for case types in cases-management BO.
=> Feature/case management/case type categories in cases bo

src/Indice.Features.Cases.App/src/app/features/cases/cases.component.html
Αλλαγη των headers στο Cases App καρφωτα, μεχρι να υλοποιηθει configurable option.
=> Change headers in Cases App

src/Indice.Features.Cases.App/src/app/features/cases/case-create-page/case-create-page.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/cases.component.html, src/Indice.Features.Cases.App/src/app/features/cases/cases.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/queries-page/queries-page.component.html, src/Indice.Features.Cases.App/src/app/features/cases/queries-page/queries-page.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/delete-query-modal/delete-query-modal.component.html, src/Indice.Features.Cases.App/src/app/shared/components/delete-query-modal/delete-query-modal.component.ts, src/Indice.Features.Cases.App/src/app/shared/components/search-customer/search-customer.component.html, src/Indice.Features.Cases.App/src/app/shared/shared.module.ts
=> ui fixes for queries

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/CasesApiConstants.cs, src/Indice.Features.Cases.AspNetCore/Data/Models/AuditMeta.cs, src/Indice.Features.Cases.AspNetCore/Extensions/PrincipalExtensions.cs, src/Indice.Features.Cases.AspNetCore/Services/BaseCaseService.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseMessageService/BaseCaseMessageService.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseMessageService/MyCaseMessageService.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
Modified Populate class to get client id as fallback if subject is null 
Created FindSubjectIdOrClientId to get client id if subject is null 
Applied new method were appropriate
=> AuditMeta changes

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseMessageService/AdminCaseMessageService.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
Added property in GetMyCasesListFilter
Modified get cases code to use new filter
=> Fetch draft cases

src/Indice.Common/Types/CountryInfo.cs
In order to have consistency, an empty space from CountryInfo was deleted
=> delete empty space from CountryInfo

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Indice.Features.Cases.AspNetCore.csproj, src/Indice.Features.Cases.AspNetCore/Services/SchemaValidator.cs
- Elsa updates to `2.11.1`.
- JsonSchema.Net to `4.1.1`.
=> Update CaseApi packages to latest

src/Indice.Features.Cases.AspNetCore/Services/MemberAuthorizationService.cs
Read API scope from admin options at `IsValid` method instead of constant value.
=> MemberAuthService fix

src/Indice.Features.Cases.App/package.json, src/Indice.Features.Cases.App/src/app/app.component.ts, src/Indice.Features.Cases.App/src/app/app.module.ts, src/Indice.Features.Cases.App/src/app/core/models/settings.model.ts, src/Indice.Features.Cases.App/src/app/core/models/settings.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html, src/Indice.Features.Cases.App/src/app/features/cases/cases.component.html, src/Indice.Features.Cases.App/src/app/features/dashboard/dashboard.component.html, src/Indice.Features.Cases.App/src/app/shared/components/case-detail-info/case-detail-info.component.html, src/Indice.Features.Cases.App/src/app/shared/shared.module.ts, src/Indice.Features.Cases.App/src/assets/i18n/el.json, src/Indice.Features.Cases.App/src/environments/environment.prod.ts, src/Indice.Features.Cases.App/src/environments/environment.template.ts, src/Indice.Features.Cases.App/src/environments/environment.ts, src/Indice.Features.Cases.UI/CHANGELOG.md, src/Indice.Features.Cases.UI/CasesUIOptions.cs, src/Indice.Features.Cases.UI/cases-app/index.html
Fixes #252
> Example to override default el.json file
```cs
app.UseCasesUI(options => {
// This is the absolute path to the folder that contains the el.json
options.I18nAssets = "/assets/cases/i18n";
});
=> Add translation support to cases ui

src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.html, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/file-widget/file-widget.component.html, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/submit-widget/submit-widget.component.ts, src/Indice.Features.Cases.App/src/styles.scss, src/Indice.Features.Cases.App/tailwind.config.js
- We had to override ng-indice default button behavior regarding `background-color: transparent
- We set dark theme with class at `tailwind.js` in order to force light theme and fix timeline issues
=> tailwind fixes

src/Indice.Features.Identity.UI/Pages/AddEmail.cshtml.cs, src/Indice.Features.Identity.UI/Resources/Pages/AddEmailModel.el.resx, src/Indice.Features.Identity.UI/Resources/Pages/Shared/EmailConfirmYourEmail.el.resx, src/Indice.Features.Identity.UI/Resources/Pages/VerifyPhone.el.resx
Fix typos
Add missing translation
=> fix translations

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/href-widget/href-widget.component.html, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/href-widget/href-widget.component.ts, src/Indice.Features.Cases.App/src/app/shared/shared.module.ts, src/Indice.Features.Cases.UI/CHANGELOG.md
Some clients need to have clickable links in their readonly form
=> add href ajsf widget in cases back-office

src/Indice.Features.Cases.AspNetCore/CasesApiFeatureExtensions.cs, src/Indice.Features.Cases.AspNetCore/Extensions/PrincipalExtensions.cs, src/Indice.Features.Cases.AspNetCore/Models/GetMyCasesListFilter.cs, src/Indice.Features.Cases.AspNetCore/Models/Responses/MyCasePartial.cs, src/Indice.Features.Cases.AspNetCore/Services/MyCaseService.cs
Adds the `IncludeData` option in the `GetMyCasesListFilter`.
PrincipalExtensions `SystemUser()` fix.
=> MyCasesListFilter IncludeData flag

.github/workflows/codeql.yml, build.ps1
Add CodeQL workflow YML enabling support for code analysis for both JavaScript/Typescript and .NET projects.
- Each project must be built before the analysis execution.
=> Add CodeQL analysis

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/CasesApiFeatureExtensions.cs
Override the default AllowAnonymoysHttpHandler by enabling the `AuthenticationBasedHttpEndpointAuthorizationHandler` and use custom authorization policies to HttpActivities
more: https://github.com/elsa-workflows/elsa-core/blob/main/src/modules/Elsa.Http/Handlers/AuthenticationBasedHttpEndpointAuthorizationHandler.cs
=> Add Elsa HttpActivities authorization handler

src/Indice.Features.Messages.App/src/app/features/campaigns/create/steps/basic-info/campaign-basic-info.component.ts, src/Indice.Features.Messages.App/src/app/features/campaigns/edit/details/rightpane/campaign-edit-details-rightpane.component.ts
=> Date formatting changes

src/Indice.Features.Risk.Core/Abstractions/IRiskEventStore.cs, src/Indice.Features.Risk.Core/Abstractions/IRiskResultStore.cs, src/Indice.Features.Risk.Core/Data/Models/DbAggregateRuleExecutionResult.cs, src/Indice.Features.Risk.Core/Extensions/IServiceCollectionExtensions.cs, src/Indice.Features.Risk.Core/Models/AdminRiskFilter.cs, src/Indice.Features.Risk.Core/RuleExecutionResults.cs, src/Indice.Features.Risk.Core/Services/RiskManager.cs, src/Indice.Features.Risk.Core/Stores/RiskEventStoreEntityFrameworkCore.cs, src/Indice.Features.Risk.Core/Stores/RiskEventStoreNoOp.cs, src/Indice.Features.Risk.Core/Stores/RiskResultStoreEntityFrameworkCore.cs, src/Indice.Features.Risk.Server/AdminRiskApi.cs, src/Indice.Features.Risk.Server/AdminRiskApiHandlers.cs, test/Indice.Features.Risk.Tests/RiskCalculationTests.cs
- Register Admin Risk endpoints for fetching Risk Events and Risk Results from Risk Store
=> Add Admin Risk endpoints

src/Indice.Features.Risk.Core/Abstractions/IRiskEventStore.cs, src/Indice.Features.Risk.Core/Stores/RiskEventStoreEntityFrameworkCore.cs, src/Indice.Features.Risk.Core/Stores/RiskEventStoreNoOp.cs, test/Indice.Features.Risk.Tests/RiskCalculationTests.cs
- Introduce _GetHistoricalRiskEvents_ fetch db data method.
=> Introduce Fetching of Historical Risk Events

src/Directory.Build.props, src/Indice.Features.Risk.App/src/app/core/services/risk-api.service.ts, src/Indice.Features.Risk.App/src/app/shared/rule-options-page/rule-options-page.component.html, src/Indice.Features.Risk.App/src/app/shared/rule-options-page/rule-options-page.component.ts, src/Indice.Features.Risk.Core/Extensions/IServiceCollectionExtensions.cs, src/Indice.Features.Risk.Core/Models/RuleOptions.cs, src/Indice.Features.Risk.Core/Services/AdminRuleService.cs, src/Indice.Features.Risk.Core/Services/RiskService.cs, src/Indice.Features.Risk.Core/Services/RiskStoreService.cs, src/Indice.Features.Risk.Core/Stores/RuleStoreEntityFrameworkCore.cs, src/Indice.Features.Risk.Server/AdminRiskApiHandlers.cs, src/Indice.Features.Risk.Server/RiskApiHandlers.cs, test/Indice.Features.Risk.Tests/RiskCalculationTests.cs
- Performance refactor, separating functionality into different services, minimizing DI overhead when not needed
- Bugfixes in BackOffice client
- Risk tests fixed
=> Risk engine and BackOffice improvements

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs, src/Indice.Features.Cases.AspNetCore/Interfaces/ICaseActionsService.cs, src/Indice.Features.Cases.AspNetCore/Services/CaseActionsService.cs
Allow System Client to access case actions.
=> Allow SystemClient to GetUserActions

src/Indice.Features.Cases.App/package.json, src/Indice.Features.Cases.App/src/app/app-routing.module.ts, src/Indice.Features.Cases.App/src/app/app.links.ts, src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts, src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.html, src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.ts
The selected specific case type that is selected by the side navbar menu (navlinks) is now being displayed in the title
=> Feature/case management/show case type in title

src/Directory.Build.props, src/Indice.Features.GovGr/Indice.Features.GovGr.csproj
=> Add govgr version

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs, src/Indice.Features.Cases.AspNetCore/Models/SendMessageRequest.cs
Added a new endpoint in Admin Controller to allow user to send messages and reply to an existing message.
=> Add endpoint to support adding a new message

src/Indice.Services/PushNotificationServiceAzure.cs
- fcm legacy is not supported, all clients must migrate to the new template
- internal console will be provided
=> Fix android template to support fcm v1

src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Cases.AspNetCore/Controllers/AdminAccessRulesController.cs, src/Indice.Features.Cases.AspNetCore/Extensions/PrincipalExtensions.cs, src/Indice.Features.Cases.AspNetCore/Interfaces/IAccessRuleService.cs, src/Indice.Features.Cases.AspNetCore/Services/AccessRuleService.cs, src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs, test/Indice.Features.Cases.AspNetCore.Tests/AccessRulesServiceTest.cs
Added support to get case rules
Fix in query for results
Use GroupId in query
=> Access rules extentions

src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/file-widget/file-widget.component.ts, src/Indice.Features.Cases.AspNetCore/Controllers/AdminAttachmentsController.cs
Download file button downloads the file instead of opening to new tab
=> File-widget download button fix

src/Directory.Build.props, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-form/case-form.component.ts, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/file-widget/file-widget.component.html, src/Indice.Features.Cases.App/src/app/shared/ajsf/json-schema-frameworks/tailwind-framework/file-widget/file-widget.component.ts, src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
Δοκιμαστικα σεναρια
Στο layout εχουμε 2 file attachment fields, και 2 input fields.
Σεναριο 1:
Στο draft case ανεβαζω το 1ο αρχείο και αφήνω όλα τα πεδία κενά. Παταω δημιουργία υπόθεσης. Στο edit case βάζω το 2ο αρχείο και πατάω αποθήκευση.
bug: την στιγμή που κάνω choose file και διαλέξω ένα αρχείο, το κουμπι μετατρεπετε σε "download" και αν το πατησω δεν κανει κατι
Σεναριο 2:
Στο draft case ανεβάζω το 2ο αρχείο και αφηνω ολα τα πεδια κενα. Παταω δημιουργία υποθεσης. Στο edit case βαζω το 1ο αρχείο, συμπληρώνω όλα τα πεδία και παταω αποθηκευση.
Σεναριο 3:
Στο draft case πατάω δημιουργία υπόθεσης χωρις να βαλω τιποτα. Στο edit case βάζω και τα 2 αρχεία και συμπληρώνω όλα τα πεδία.
Σεναριο 4:
Στο draft case ανεβάζω το 1ο αρχείο, πατάω δημιουργια υποθεσης. Βγαινω εξω απο το case και …
=> Upload files during case edit

src/Directory.Build.props, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-timeline/case-timeline.component.html, src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-timeline/case-timeline.component.ts, src/Indice.Features.Cases.AspNetCore/CHANGELOG.md
Added hideStatuses flag to hide the status badges in the timeline component
=> Hide statuses in timeline

src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.html, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.scss, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.ts, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/user-edit.component.ts, src/Indice.Features.Identity.AdminUI.App/src/app/layout/components/dashboard-shell/top-bar/top-bar.component.ts
This PR addresses the following:
- Added ability to zoom
- Added bounds detection for images when zoomed
- Added success and failure toast notification on submission
- Fixed bugs with parameter mismatches sent to server for cropping
=> User profile picture feature enhancements

src/Directory.Build.props, src/Indice.Features.Cases.AspNetCore/CHANGELOG.md, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.html, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.scss, src/Indice.Features.Identity.AdminUI.App/src/app/features/users/edit/profile-picture/profile-picture.component.ts
This PR includes:
- Ability to delete profile picture from inside the modal
- Ability to change profile picture from inside the modal
- UI improvements
- Handling zoom out to stay within bounds
=> Edit and delete profile picture

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/related-cases/related-cases.component.html, src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs, src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
Limiting the container to 7 rows
=> Related case container is now scrollable

src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
Fetching related cases will no longer include the current case
=> Excluding current case from related cases

src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/related-cases/related-cases.component.html
Changed the design of the related cases
=> Related cases UI change

src/Indice.Features.Cases.AspNetCore/Controllers/AdminCaseDataController.cs, src/Indice.Features.Cases.AspNetCore/Interfaces/IAdminCaseService.cs, src/Indice.Features.Cases.AspNetCore/Models/PatchJsonPathRequest.cs, src/Indice.Features.Cases.AspNetCore/Models/Requests/AddCaseAccessRuleRequest.cs
@cleftheris 
1. Have we started using <nullable> here in preparation for future dropping support?
2. I didn't bump up version, right?
=> [CasesApi] Resolve introduced compiler warnings

src/Indice.Services/Extensions/IServiceCollectionExtensions.cs, src/Indice.Services/SmsServiceApifon.cs, src/Indice.Services/SmsServiceApifonIM.cs, src/Indice.Services/ViberServiceApifon.cs, test/Indice.Services.Tests/SmsTests.cs
Implement an Apifon `ISmsService` in order to support both Viber and SMS fallback.
=> Add Apifon Viber with SMS fallback provider
